import type { SummaryEngineConfig } from "./types.js";

export const defaultConfig: SummaryEngineConfig = {
  prefix: "[Support]",
  maxTitleLength: 100,
  fallbackSuffix: "Support Request",
  fallbackNewTicket: "New Support Ticket",
  unknownCustomerValues: ["unknown", "unknown customer", "unknown company", "n/a"],
  genericSummaryPhrases: [
    "help",
    "support",
    "issue",
    "problem",
    "urgent",
    "ticket",
    "need help",
    "need support",
    "please help",
    "can you help",
    "assistance",
  ],
  issueKeywords: [
    "login",
    "log in",
    "sign in",
    "signin",
    "password",
    "otp",
    "2fa",
    "authentication",
    "auth",
    "payment",
    "billing",
    "invoice",
    "checkout",
    "error",
    "failed",
    "failure",
    "cannot",
    "can't",
    "unable",
    "timeout",
    "locked",
    "access",
    "account",
    "crash",
    "broken",
    "upload",
    "download",
    "webhook",
    "api",
    "integration",
    "notification",
    "email",
    "sso",
    "mfa",
    "display",
    "slow",
    "delayed",
    "subscription",
    "charge",
    "refund",
    "502",
    "403",
    "500",
    "503",
    "404",
    "connection",
    "database",
    "query",
    "queries",
    "stale",
    "missing",
    "empty",
    "failing",
    "expired",
  ],
  rootCausePatterns: [
    /\bnot\s+arriv(ing|ed)?\b/i,
    /\bnot\s+receiv(ing|ed)?\b/i,
    /\bdoes\s+not\b/i,
    /\bdon't\b/i,
    /\bcan't\b/i,
    /\bcannot\b/i,
    /\bunable\b/i,
    /\bfailed\b/i,
    /\berror\b/i,
    /\btimeout\b/i,
    /\binvalid\b/i,
    /\bnot\s+work(ing|ed|s)?\b/i,
    /\bnot\s+render(ing|ed|s)?\b/i,
    /\bnot\s+load(ing|ed|s)?\b/i,
    /\bnot\s+show(ing|n)?\b/i,
    /\bnot\s+display(ing|ed)?\b/i,
    /\bnot\s+send(ing)?\b/i,
    /\b(time[sd]?|timing)\s+out\b/i,
    /\bcrash(es|ed|ing)?\b/i,
    /\bbroken\b/i,
    /\bincorrect(ly)?\b/i,
    /\b(returns?|returning)\s+(no\s+results?|empty|null|404|403|500|502|503)\b/i,
    /\bfailing\b/i,
  ],
  impactOnlyPatterns: [
    /\blocked\s+out\b/i,
    /\bblocked\b/i,
    /\bcannot\s+access\b/i,
    /\bunable\s+to\s+access\b/i,
    /\bfor\s+urgent\s+tasks\b/i,
    /\bbusiness\s+impact\b/i,
  ],
  contextOnlyPatterns: [
    /^we\s+enabled\b/i,
    /^we\s+updated\b/i,
    /^for\s+security\b/i,
    /^after\s+/i,
    /^hope\s+you.re\s+doing\s+well\b/i,
    /^we.ve\s+been\s+using\b/i,
    /^i\s+love\b/i,
    /^great\s+product\b/i,
    /^this\s+is\s+\w+\s+from\b/i,
  ],
  leadingFillerPatterns: [
    /^(hi|hello|hey)(\s+(team|support|there))?[\s,.:!\-]*/i,
    /^(please|pls)\s+/i,
    /^(i have an issue with|i have an issue|i have problem with|i have a problem with)\s+/i,
    /^(i need help with|i need help|need help with|need help)\s+/i,
    /^(issue[:\-]\s*)/i,
    /^(problem[:\-]\s*)/i,
    /^(i\s+just\s+wanted\s+to\s+(reach\s+out|let\s+you\s+know|report|inform\s+you)(\s+(because|that))?)\s*/i,
    /^(just\s+wanted\s+to\s+(reach\s+out|let\s+you\s+know|report)(\s+that)?)\s*/i,
    /^(i\s+wanted\s+to\s+(report|let\s+you\s+know|reach\s+out|inform\s+you)(\s+that)?)\s*/i,
    /^(i('m|\s+am)\s+experiencing)\s+/i,
    /^(we('re|\s+are)\s+experiencing)\s+/i,
    /^(we('re|\s+are)\s+facing(\s+issues?\s+with)?)\s+/i,
    /^(i('m|\s+am)\s+having\s+(trouble|issues?|problems?)\s+with)\s+/i,
    /^(we\s+noticed\s+that)\s+/i,
    /^(a\s+)?(critical\s+|major\s+|minor\s+|serious\s+)?(bug|issue|problem|error)\s+(where|that)\s+/i,
    /^(this\s+is\s+ridiculous|this\s+is\s+unacceptable)[.!,\s]*/i,
  ],
  trailingFillerPatterns: [
    /[\s,.-]*(please|pls)\s+help(\s+me)?[\s,.-]*$/i,
    /[\s,.-]*(can\s+you\s+help(\s+me)?)[\s,.-]*$/i,
    /[\s,.-]*(need\s+help|support\s+please)[\s,.-]*$/i,
  ],
  conjunctionStripPatterns: [/^\s*(but|and|also)\s+/i],
  causalSplitPattern: /\b(because|since|as|while|even though|although|so that)\b/i,
};

export function withPrefix(config: SummaryEngineConfig, prefix: string): SummaryEngineConfig {
  return {
    ...config,
    prefix,
  };
}
